apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-dev
  namespace: argocd
spec:
  project: web-platform
  source:
    repoURL: 'https://github.com/jackm-g/argocd-demo.git'
    targetRevision: main
    path: infra/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: web
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true