apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: web
spec:
  replicas: 1
  selector: { matchLabels: { app: celery-worker } }
  template:
    metadata: { labels: { app: celery-worker } }
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: worker
          image: cgm-django-api:dev-1
          command: ["celery"]
          args: ["-A","config.celery_app","worker","--loglevel=INFO","--concurrency=2"]
          env:
            - { name: CELERY_BROKER_URL, value: "redis://redis.web.svc.cluster.local:6379/0" }
            - { name: DJANGO_SETTINGS_MODULE, value: config.settings }
          imagePullPolicy: IfNotPresent